/**:
  ros__parameters:
    use_sim_time: True
  platform:
    ros__parameters:
      cmd_freq: 30.0  # Hz of platform commands send
      info_freq: 10.0  # Hz of platform info publish
      enable_takeoff_platform: false  # Enable takeoff platform, only for debugging purposes
      enable_land_platform: false  # Enable land platform, only for debugging purposes
  state_estimator:
    ros__parameters:
      plugin_name: ground_truth
      use_gazebo_tf: True
  controller_manager:
    ros__parameters:
      plugin_name: pid_speed_controller
      cmd_freq: 100.0  # Hz of platform commands send
      info_freq: 10.0  # Hz of platform info publish
      odom_frame_id: "odom"
      base_frame_id: "base_link"
      use_bypass: true
      tf_timeout_threshold: 0.5 # Default tf timeout (50ms)
  TakeoffBehavior:
    ros__parameters:
      takeoff_plugin_name: takeoff_plugin_trajectory
      takeoff_height: 1.0 # Default takeoff height
      takeoff_speed: 0.5 # Default takeoff speed
      takeoff_threshold: 0.2 # Default takeoff threshold
      tf_timeout_threshold: 0.5 # Default tf timeout (50ms)
  LandBehavior:
    ros__parameters:
      land_plugin_name: land_plugin_speed
      land_speed: 0.5 # Default land speed
      land_speed_condition_percentage: 0.2 # Speed condition to finish land. Only used with land_plugin_speed and land_plugin_trajectory
      land_speed_condition_height: 0.2 # Height condition to finish land. Only used with land_plugin_speed and land_plugin_trajectory
      land_trajectory_height: -10.0 # Height send to trajectory generator. Only used with land_plugin_trajectory
      tf_timeout_threshold: 0.5 # Default tf timeout (50ms)
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: go_to_plugin_trajectory
      go_to_speed: 0.5 # Default go_to speed
      go_to_threshold: 0.2 # Default go_to threshold
      tf_timeout_threshold: 0.5 # Default tf timeout (50ms)
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: follow_path_plugin_trajectory
      follow_path_speed: 0.5 # Default follow_path speed
      follow_path_threshold: 0.2 # Default follow_path threshold
      tf_timeout_threshold: 0.5 # Default tf timeout (50ms)