/**:
  ros__parameters:
    use_sim_time: False
  platform:
    ros__parameters:
      cmd_freq: 100.0  # Hz of platform commands send
      info_freq: 10.0  # Hz of platform info publish
      external_odom: true  # Availability of external odometry
      external_odom_topic: "self_localization/pose" # External odometry topic name
      controller_type: 1  # Controller type Any(0), PID(1), Mellinger(2), INDI(3)
      estimator_type: 2 # Estimator type Any(0), complementary(1), kalman(2)
  state_estimator:
    ros__parameters:
      plugin_name: mocap_pose
      mocap_topic: "/mocap/rigid_bodies"
      twist_smooth_filter_cte: 0.1
      orientation_smooth_filter_cte: 0.1
  controller_manager:
    ros__parameters:
      plugin_name: pid_speed_controller
      cmd_freq: 100.0  # Hz of platform commands send
      info_freq: 10.0  # Hz of platform info publish
      odom_frame_id: "odom"
      base_frame_id: "base_link"
      use_bypass: true
      tf_timeout_threshold: 0.05  # seconds
  TakeoffBehavior:
    ros__parameters:
      takeoff_plugin_name: takeoff_plugin_trajectory
      takeoff_height: 1.0 # Default takeoff height
      takeoff_speed: 0.5 # Default takeoff speed
      takeoff_threshold: 0.2 # Default takeoff threshold
      tf_timeout_threshold: 0.5 # Default tf timeout (50ms)
  LandBehavior:
    ros__parameters:
      land_plugin_name: land_plugin_speed
      land_speed: 0.5 # Default land speed
      land_speed_condition_percentage: 0.2 # Speed condition to finish land. Only used with land_plugin_speed and land_plugin_trajectory
      land_speed_condition_height: 0.2 # Height condition to finish land. Only used with land_plugin_speed and land_plugin_trajectory
      land_trajectory_height: -10.0 # Height send to trajectory generator. Only used with land_plugin_trajectory
      tf_timeout_threshold: 0.5 # Default tf timeout (50ms)
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: go_to_plugin_trajectory
      go_to_speed: 0.5 # Default go_to speed
      go_to_threshold: 0.3 # Default go_to threshold
      tf_timeout_threshold: 0.5 # Default tf timeout (50ms)
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: follow_path_plugin_trajectory
      follow_path_speed: 0.5 # Default follow_path speed
      follow_path_threshold: 0.2 # Default follow_path threshold
      tf_timeout_threshold: 0.5 # Default tf timeout (50ms)
cf0:
  state_estimator:
    ros__parameters:
      rigid_body_name: '1'
cf1:
  state_estimator:
    ros__parameters:
      rigid_body_name: '2'
cf2:
  state_estimator:
    ros__parameters:
      rigid_body_name: '3'